linux: Linux-2.6.12-rc2
Commit: 1da177e4c3f41524e886b7f1b8a0c1fc7321cac2

diff --git a/linux/scripts/extract-ikconfig b/linux/scripts/extract-ikconfig
--- a/linux/scripts/extract-ikconfig
+++ b/linux/scripts/extract-ikconfig
@@ -1,68 +1,77 @@
 #!/bin/sh
-# ----------------------------------------------------------------------
-# extract-ikconfig - Extract the .config file from a kernel image
-#
-# This will only work when the kernel was compiled with CONFIG_IKCONFIG.
-#
-# The obscure use of the "tr" filter is to work around older versions of
-# "grep" that report the byte offset of the line instead of the pattern.
-#
-# (c) 2009,2010 Dick Streefland <dick@streefland.net>
-# Licensed under the terms of the GNU General Public License.
-# ----------------------------------------------------------------------
+# extracts .config info from a [b]zImage file
+# uses: binoffset (new), dd, zcat, strings, grep
+# $arg1 is [b]zImage filename
 
-cf1='IKCFG_ST\037\213\010'
-cf2='0123456789'
+binoffset="./scripts/binoffset"
 
-dump_config()
+IKCFG_ST="0x49 0x4b 0x43 0x46 0x47 0x5f 0x53 0x54"
+IKCFG_ED="0x49 0x4b 0x43 0x46 0x47 0x5f 0x45 0x44"
+function dump_config {
+    typeset file="$1"
+
+    start=`$binoffset $file $IKCFG_ST 2>/dev/null`
+    [ "$?" != "0" ] && start="-1"
+    if [ "$start" -eq "-1" ]; then
+	return
+    fi
+    end=`$binoffset $file $IKCFG_ED 2>/dev/null`
+
+    let start="$start + 8"
+    let size="$end - $start"
+
+    head --bytes="$end" "$file" | tail --bytes="$size" | zcat
+
+    clean_up
+    exit 0
+}
+
+
+usage()
 {
-	if	pos=`tr "$cf1\n$cf2" "\n$cf2=" < "$1" | grep -abo "^$cf2"`
-	then
-		pos=${pos%%:*}
-		tail -c+$(($pos+8)) "$1" | zcat > $tmp1 2> /dev/null
-		if	[ $? != 1 ]
-		then	# exit status must be 0 or 2 (trailing garbage warning)
-			cat $tmp1
-			exit 0
-		fi
+	echo "  usage: extract-ikconfig [b]zImage_filename"
+}
+
+clean_up()
+{
+	if [ "$TMPFILE" != "" ]; then
+		rm -f $TMPFILE
 	fi
 }
 
-try_decompress()
-{
-	for	pos in `tr "$1\n$2" "\n$2=" < "$img" | grep -abo "^$2"`
-	do
-		pos=${pos%%:*}
-		tail -c+$pos "$img" | $3 > $tmp2 2> /dev/null
-		dump_config $tmp2
-	done
-}
-
-# Check invocation:
-me=${0##*/}
-img=$1
-if	[ $# -ne 1 -o ! -s "$img" ]
+if [ $# -lt 1 ]
 then
-	echo "Usage: $me <kernel-image>" >&2
-	exit 2
+	usage
+	exit 1
 fi
 
-# Prepare temp files:
-tmp1=/tmp/ikconfig$$.1
-tmp2=/tmp/ikconfig$$.2
-trap "rm -f $tmp1 $tmp2" 0
+TMPFILE="/tmp/ikconfig-$$"
+image="$1"
 
-# Initial attempt for uncompressed images or objects:
-dump_config "$img"
+# vmlinux: Attempt to dump the configuration from the file directly
+dump_config "$image"
 
-# That didn't work, so retry after decompression.
-try_decompress '\037\213\010' xy    gunzip
-try_decompress '\3757zXZ\000' abcde unxz
-try_decompress 'BZh'          xy    bunzip2
-try_decompress '\135\0\0\0'   xxx   unlzma
-try_decompress '\211\114\132' xy    'lzop -d'
-try_decompress '\002\041\114\030' xyy 'lz4 -d -l'
+GZHDR1="0x1f 0x8b 0x08 0x00"
+GZHDR2="0x1f 0x8b 0x08 0x08"
 
-# Bail out:
-echo "$me: Cannot find kernel config." >&2
+# vmlinux.gz: Check for a compressed images
+off=`$binoffset "$image" $GZHDR1 2>/dev/null`
+[ "$?" != "0" ] && off="-1"
+if [ "$off" -eq "-1" ]; then
+	off=`$binoffset "$image" $GZHDR2 2>/dev/null`
+	[ "$?" != "0" ] && off="-1"
+fi
+if [ "$off" -eq "0" ]; then
+	zcat <"$image" >"$TMPFILE"
+	dump_config "$TMPFILE"
+elif [ "$off" -ne "-1" ]; then
+	(dd ibs="$off" skip=1 count=0 && dd bs=512k) <"$image" 2>/dev/null | \
+		zcat >"$TMPFILE"
+	dump_config "$TMPFILE"
+fi
+
+echo "ERROR: Unable to extract kernel configuration information."
+echo "       This kernel image may not have the config info."
+
+clean_up
 exit 1
diff --git a/linux/scripts/kconfig/Makefile b/linux/scripts/kconfig/Makefile
--- a/linux/scripts/kconfig/Makefile
+++ b/linux/scripts/kconfig/Makefile
@@ -1,214 +1,208 @@
-# SPDX-License-Identifier: GPL-2.0
 # ===========================================================================
 # Kernel configuration targets
 # These targets are used from top-level makefile
 
-ifdef KBUILD_KCONFIG
-Kconfig := $(KBUILD_KCONFIG)
-else
-Kconfig := Kconfig
-endif
+.PHONY: oldconfig xconfig gconfig menuconfig config silentoldconfig
 
-ifndef KBUILD_DEFCONFIG
-KBUILD_DEFCONFIG := defconfig
-endif
+xconfig: $(obj)/qconf
+	$< arch/$(ARCH)/Kconfig
 
-ifeq ($(quiet),silent_)
-silent := -s
-endif
+gconfig: $(obj)/gconf
+	$< arch/$(ARCH)/Kconfig
 
-export KCONFIG_DEFCONFIG_LIST :=
-ifndef cross_compiling
-kernel-release := $(shell uname -r)
-KCONFIG_DEFCONFIG_LIST += \
-	/lib/modules/$(kernel-release)/.config \
-	/etc/kernel-config \
-	/boot/config-$(kernel-release)
-endif
-KCONFIG_DEFCONFIG_LIST += arch/$(SRCARCH)/configs/$(KBUILD_DEFCONFIG)
+menuconfig: $(obj)/mconf
+	$(Q)$(MAKE) $(build)=scripts/lxdialog
+	$< arch/$(ARCH)/Kconfig
 
-# We need this, in case the user has it in its environment
-unexport CONFIG_
+config: $(obj)/conf
+	$< arch/$(ARCH)/Kconfig
 
-config-prog	:= conf
-menuconfig-prog	:= mconf
-nconfig-prog	:= nconf
-gconfig-prog	:= gconf
-xconfig-prog	:= qconf
+oldconfig: $(obj)/conf
+	$< -o arch/$(ARCH)/Kconfig
 
-define config_rule
-PHONY += $(1)
-$(1): $(obj)/$($(1)-prog)
-	$(Q)$$< $(silent) $(Kconfig)
+silentoldconfig: $(obj)/conf
+	$< -s arch/$(ARCH)/Kconfig
 
-PHONY += build_$(1)
-build_$(1): $(obj)/$($(1)-prog)
-endef
+.PHONY: randconfig allyesconfig allnoconfig allmodconfig defconfig
 
-$(foreach c, config menuconfig nconfig gconfig xconfig, $(eval $(call config_rule,$(c))))
+randconfig: $(obj)/conf
+	$< -r arch/$(ARCH)/Kconfig
 
-PHONY += localmodconfig localyesconfig
-localyesconfig localmodconfig: $(obj)/conf
-	$(Q)$(PERL) $(srctree)/$(src)/streamline_config.pl --$@ $(srctree) $(Kconfig) > .tmp.config
-	$(Q)if [ -f .config ]; then 				\
-		cmp -s .tmp.config .config ||			\
-		(mv -f .config .config.old.1;			\
-		 mv -f .tmp.config .config;			\
-		 $< $(silent) --oldconfig $(Kconfig);		\
-		 mv -f .config.old.1 .config.old)		\
-	else							\
-		mv -f .tmp.config .config;			\
-		$< $(silent) --oldconfig $(Kconfig);		\
-	fi
-	$(Q)rm -f .tmp.config
+allyesconfig: $(obj)/conf
+	$< -y arch/$(ARCH)/Kconfig
 
-# These targets map 1:1 to the commandline options of 'conf'
-#
-# Note:
-#  syncconfig has become an internal implementation detail and is now
-#  deprecated for external use
-simple-targets := oldconfig allnoconfig allyesconfig allmodconfig \
-	alldefconfig randconfig listnewconfig olddefconfig syncconfig \
-	helpnewconfig yes2modconfig mod2yesconfig mod2noconfig
+allnoconfig: $(obj)/conf
+	$< -n arch/$(ARCH)/Kconfig
 
-PHONY += $(simple-targets)
-
-$(simple-targets): $(obj)/conf
-	$(Q)$< $(silent) --$@ $(Kconfig)
-
-PHONY += savedefconfig defconfig
-
-savedefconfig: $(obj)/conf
-	$(Q)$< $(silent) --$@=defconfig $(Kconfig)
+allmodconfig: $(obj)/conf
+	$< -m arch/$(ARCH)/Kconfig
 
 defconfig: $(obj)/conf
-ifneq ($(wildcard $(srctree)/arch/$(SRCARCH)/configs/$(KBUILD_DEFCONFIG)),)
-	@$(kecho) "*** Default configuration is based on '$(KBUILD_DEFCONFIG)'"
-	$(Q)$< $(silent) --defconfig=arch/$(SRCARCH)/configs/$(KBUILD_DEFCONFIG) $(Kconfig)
+ifeq ($(KBUILD_DEFCONFIG),)
+	$< -d arch/$(ARCH)/Kconfig
 else
-	@$(kecho) "*** Default configuration is based on target '$(KBUILD_DEFCONFIG)'"
-	$(Q)$(MAKE) -f $(srctree)/Makefile $(KBUILD_DEFCONFIG)
+	@echo *** Default configuration is based on '$(KBUILD_DEFCONFIG)'
+	$(Q)$< -D arch/$(ARCH)/configs/$(KBUILD_DEFCONFIG) arch/$(ARCH)/Kconfig
 endif
 
 %_defconfig: $(obj)/conf
-	$(Q)$< $(silent) --defconfig=arch/$(SRCARCH)/configs/$@ $(Kconfig)
-
-configfiles=$(wildcard $(srctree)/kernel/configs/$@ $(srctree)/arch/$(SRCARCH)/configs/$@)
-
-%.config: $(obj)/conf
-	$(if $(call configfiles),, $(error No configuration exists for this target on this architecture))
-	$(Q)$(CONFIG_SHELL) $(srctree)/scripts/kconfig/merge_config.sh -m .config $(configfiles)
-	$(Q)$(MAKE) -f $(srctree)/Makefile olddefconfig
-
-PHONY += tinyconfig
-tinyconfig:
-	$(Q)KCONFIG_ALLCONFIG=kernel/configs/tiny-base.config $(MAKE) -f $(srctree)/Makefile allnoconfig
-	$(Q)$(MAKE) -f $(srctree)/Makefile tiny.config
-
-# CHECK: -o cache_dir=<path> working?
-PHONY += testconfig
-testconfig: $(obj)/conf
-	$(Q)$(PYTHON3) -B -m pytest $(srctree)/$(src)/tests \
-	-o cache_dir=$(abspath $(obj)/tests/.cache) \
-	$(if $(findstring 1,$(KBUILD_VERBOSE)),--capture=no)
-clean-files += tests/.cache
+	$(Q)$< -D arch/$(ARCH)/configs/$@ arch/$(ARCH)/Kconfig
 
 # Help text used by make help
 help:
 	@echo  '  config	  - Update current config utilising a line-oriented program'
-	@echo  '  nconfig         - Update current config utilising a ncurses menu based program'
 	@echo  '  menuconfig	  - Update current config utilising a menu based program'
-	@echo  '  xconfig	  - Update current config utilising a Qt based front-end'
-	@echo  '  gconfig	  - Update current config utilising a GTK+ based front-end'
+	@echo  '  xconfig	  - Update current config utilising a QT based front-end'
+	@echo  '  gconfig	  - Update current config utilising a GTK based front-end'
 	@echo  '  oldconfig	  - Update current config utilising a provided .config as base'
-	@echo  '  localmodconfig  - Update current config disabling modules not loaded'
-	@echo  '                    except those preserved by LMC_KEEP environment variable'
-	@echo  '  localyesconfig  - Update current config converting local mods to core'
-	@echo  '                    except those preserved by LMC_KEEP environment variable'
-	@echo  '  defconfig	  - New config with default from ARCH supplied defconfig'
-	@echo  '  savedefconfig   - Save current config as ./defconfig (minimal config)'
-	@echo  '  allnoconfig	  - New config where all options are answered with no'
-	@echo  '  allyesconfig	  - New config where all options are accepted with yes'
-	@echo  '  allmodconfig	  - New config selecting modules when possible'
-	@echo  '  alldefconfig    - New config with all symbols set to default'
 	@echo  '  randconfig	  - New config with random answer to all options'
-	@echo  '  yes2modconfig	  - Change answers from yes to mod if possible'
-	@echo  '  mod2yesconfig	  - Change answers from mod to yes if possible'
-	@echo  '  mod2noconfig	  - Change answers from mod to no if possible'
-	@echo  '  listnewconfig   - List new options'
-	@echo  '  helpnewconfig   - List new options and help text'
-	@echo  '  olddefconfig	  - Same as oldconfig but sets new symbols to their'
-	@echo  '                    default value without prompting'
-	@echo  '  tinyconfig	  - Configure the tiniest possible kernel'
-	@echo  '  testconfig	  - Run Kconfig unit tests (requires python3 and pytest)'
+	@echo  '  defconfig	  - New config with default answer to all options'
+	@echo  '  allmodconfig	  - New config selecting modules when possible'
+	@echo  '  allyesconfig	  - New config where all options are accepted with yes'
+	@echo  '  allnoconfig	  - New minimal config'
 
 # ===========================================================================
+# Shared Makefile for the various kconfig executables:
+# conf:	  Used for defconfig, oldconfig and related targets
+# mconf:  Used for the mconfig target.
+#         Utilizes the lxdialog package
+# qconf:  Used for the xconfig target
+#         Based on QT which needs to be installed to compile it
+# gconf:  Used for the gconfig target
+#         Based on GTK which needs to be installed to compile it
 # object files used by all kconfig flavours
-common-objs	:= confdata.o expr.o lexer.lex.o menu.o parser.tab.o \
-		   preprocess.o symbol.o util.o
 
-$(obj)/lexer.lex.o: $(obj)/parser.tab.h
-HOSTCFLAGS_lexer.lex.o	:= -I $(srctree)/$(src)
-HOSTCFLAGS_parser.tab.o	:= -I $(srctree)/$(src)
+hostprogs-y	:= conf mconf qconf gconf
+conf-objs	:= conf.o  zconf.tab.o
+mconf-objs	:= mconf.o zconf.tab.o
 
-# conf: Used for defconfig, oldconfig and related targets
-hostprogs	+= conf
-conf-objs	:= conf.o $(common-objs)
+ifeq ($(MAKECMDGOALS),xconfig)
+	qconf-target := 1
+endif
+ifeq ($(MAKECMDGOALS),gconfig)
+	gconf-target := 1
+endif
 
-# nconf: Used for the nconfig target based on ncurses
-hostprogs	+= nconf
-nconf-objs	:= nconf.o nconf.gui.o $(common-objs)
 
-HOSTLDLIBS_nconf	= $(shell . $(obj)/nconf-cfg && echo $$libs)
-HOSTCFLAGS_nconf.o	= $(shell . $(obj)/nconf-cfg && echo $$cflags)
-HOSTCFLAGS_nconf.gui.o	= $(shell . $(obj)/nconf-cfg && echo $$cflags)
+ifeq ($(qconf-target),1)
+qconf-cxxobjs	:= qconf.o
+qconf-objs	:= kconfig_load.o zconf.tab.o
+endif
 
-$(obj)/nconf.o $(obj)/nconf.gui.o: $(obj)/nconf-cfg
+ifeq ($(gconf-target),1)
+gconf-objs	:= gconf.o kconfig_load.o zconf.tab.o
+endif
 
-# mconf: Used for the menuconfig target based on lxdialog
-hostprogs	+= mconf
-lxdialog	:= $(addprefix lxdialog/, \
-		     checklist.o inputbox.o menubox.o textbox.o util.o yesno.o)
-mconf-objs	:= mconf.o $(lxdialog) $(common-objs)
+clean-files	:= lkc_defs.h qconf.moc .tmp_qtcheck \
+		   .tmp_gtkcheck zconf.tab.c zconf.tab.h lex.zconf.c
 
-HOSTLDLIBS_mconf = $(shell . $(obj)/mconf-cfg && echo $$libs)
-$(foreach f, mconf.o $(lxdialog), \
-  $(eval HOSTCFLAGS_$f = $$(shell . $(obj)/mconf-cfg && echo $$$$cflags)))
+# generated files seem to need this to find local include files
+HOSTCFLAGS_lex.zconf.o	:= -I$(src)
+HOSTCFLAGS_zconf.tab.o	:= -I$(src)
 
-$(addprefix $(obj)/, mconf.o $(lxdialog)): $(obj)/mconf-cfg
+HOSTLOADLIBES_qconf	= -L$(QTLIBPATH) -Wl,-rpath,$(QTLIBPATH) -l$(QTLIB) -ldl
+HOSTCXXFLAGS_qconf.o	= -I$(QTDIR)/include -D LKC_DIRECT_LINK
 
-# qconf: Used for the xconfig target based on Qt
-hostprogs	+= qconf
-qconf-cxxobjs	:= qconf.o qconf-moc.o
-qconf-objs	:= images.o $(common-objs)
+HOSTLOADLIBES_gconf	= `pkg-config gtk+-2.0 gmodule-2.0 libglade-2.0 --libs`
+HOSTCFLAGS_gconf.o	= `pkg-config gtk+-2.0 gmodule-2.0 libglade-2.0 --cflags` \
+                          -D LKC_DIRECT_LINK
 
-HOSTLDLIBS_qconf	= $(shell . $(obj)/qconf-cfg && echo $$libs)
-HOSTCXXFLAGS_qconf.o	= $(shell . $(obj)/qconf-cfg && echo $$cflags)
-HOSTCXXFLAGS_qconf-moc.o = $(shell . $(obj)/qconf-cfg && echo $$cflags)
+$(obj)/conf.o $(obj)/mconf.o $(obj)/qconf.o $(obj)/gconf.o: $(obj)/zconf.tab.h
 
-$(obj)/qconf.o: $(obj)/qconf-cfg
+$(obj)/zconf.tab.h: $(src)/zconf.tab.h_shipped
+$(obj)/zconf.tab.c: $(src)/zconf.tab.c_shipped
+$(obj)/lex.zconf.c: $(src)/lex.zconf.c_shipped
 
-quiet_cmd_moc = MOC     $@
-      cmd_moc = $(shell . $(obj)/qconf-cfg && echo $$moc) $< -o $@
+$(obj)/qconf.o: $(obj)/.tmp_qtcheck
 
-$(obj)/qconf-moc.cc: $(src)/qconf.h $(obj)/qconf-cfg FORCE
-	$(call if_changed,moc)
+ifeq ($(qconf-target),1)
+MOC = $(QTDIR)/bin/moc
+QTLIBPATH = $(QTDIR)/lib
+-include $(obj)/.tmp_qtcheck
 
-targets += qconf-moc.cc
+# QT needs some extra effort...
+$(obj)/.tmp_qtcheck:
+	@set -e; for d in $$QTDIR /usr/share/qt* /usr/lib/qt*; do \
+	  if [ -f $$d/include/qconfig.h ]; then DIR=$$d; break; fi; \
+	done; \
+	if [ -z "$$DIR" ]; then \
+	  echo "*"; \
+	  echo "* Unable to find the QT installation. Please make sure that the"; \
+	  echo "* QT development package is correctly installed and the QTDIR"; \
+	  echo "* environment variable is set to the correct location."; \
+	  echo "*"; \
+	  false; \
+	fi; \
+	LIBPATH=$$DIR/lib; LIB=qt; \
+	$(HOSTCXX) -print-multi-os-directory > /dev/null 2>&1 && \
+	  LIBPATH=$$DIR/lib/$$($(HOSTCXX) -print-multi-os-directory); \
+	if [ -f $$LIBPATH/libqt-mt.so ]; then LIB=qt-mt; fi; \
+	echo "QTDIR=$$DIR" > $@; echo "QTLIBPATH=$$LIBPATH" >> $@; \
+	echo "QTLIB=$$LIB" >> $@; \
+	if [ ! -x $$DIR/bin/moc -a -x /usr/bin/moc ]; then \
+	  echo "*"; \
+	  echo "* Unable to find $$DIR/bin/moc, using /usr/bin/moc instead."; \
+	  echo "*"; \
+	  echo "MOC=/usr/bin/moc" >> $@; \
+	fi
+endif
 
-# gconf: Used for the gconfig target based on GTK+
-hostprogs	+= gconf
-gconf-objs	:= gconf.o images.o $(common-objs)
+$(obj)/gconf.o: $(obj)/.tmp_gtkcheck
 
-HOSTLDLIBS_gconf    = $(shell . $(obj)/gconf-cfg && echo $$libs)
-HOSTCFLAGS_gconf.o  = $(shell . $(obj)/gconf-cfg && echo $$cflags)
+ifeq ($(gconf-target),1)
+-include $(obj)/.tmp_gtkcheck
 
-$(obj)/gconf.o: $(obj)/gconf-cfg
+# GTK needs some extra effort, too...
+$(obj)/.tmp_gtkcheck:
+	@if `pkg-config gtk+-2.0 gmodule-2.0 libglade-2.0 --exists`; then		\
+		if `pkg-config gtk+-2.0 --atleast-version=2.0.0`; then			\
+			touch $@;								\
+		else									\
+			echo "*"; 							\
+			echo "* GTK+ is present but version >= 2.0.0 is required.";	\
+			echo "*";							\
+			false;								\
+		fi									\
+	else										\
+		echo "*"; 								\
+		echo "* Unable to find the GTK+ installation. Please make sure that"; 	\
+		echo "* the GTK+ 2.0 development package is correctly installed..."; 	\
+		echo "* You need gtk+-2.0, glib-2.0 and libglade-2.0."; 		\
+		echo "*"; 								\
+		false;									\
+	fi
+endif
 
-# check if necessary packages are available, and configure build flags
-filechk_conf_cfg = $(CONFIG_SHELL) $<
+$(obj)/zconf.tab.o: $(obj)/lex.zconf.c
 
-$(obj)/%conf-cfg: $(src)/%conf-cfg.sh FORCE
-	$(call filechk,conf_cfg)
+$(obj)/kconfig_load.o: $(obj)/lkc_defs.h
 
-clean-files += *conf-cfg
+$(obj)/qconf.o: $(obj)/qconf.moc $(obj)/lkc_defs.h
+
+$(obj)/gconf.o: $(obj)/lkc_defs.h
+
+$(obj)/%.moc: $(src)/%.h
+	$(MOC) -i $< -o $@
+
+$(obj)/lkc_defs.h: $(src)/lkc_proto.h
+	sed < $< > $@ 's/P(\([^,]*\),.*/#define \1 (\*\1_p)/'
+
+
+###
+# The following requires flex/bison
+# By default we use the _shipped versions, uncomment the following line if
+# you are modifying the flex/bison src.
+# LKC_GENPARSER := 1
+
+ifdef LKC_GENPARSER
+
+$(obj)/zconf.tab.c: $(obj)/zconf.y 
+$(obj)/zconf.tab.h: $(obj)/zconf.tab.c
+
+%.tab.c: %.y
+	bison -t -d -v -b $* -p $(notdir $*) $<
+
+lex.%.c: %.l
+	flex -P$(notdir $*) -o$@ $<
+
+endif
diff --git a/linux/scripts/patch-kernel b/linux/scripts/patch-kernel
--- a/linux/scripts/patch-kernel
+++ b/linux/scripts/patch-kernel
@@ -1,5 +1,4 @@
 #! /bin/sh
-# SPDX-License-Identifier: GPL-2.0
 # Script to apply kernel patches.
 #   usage: patch-kernel [ sourcedir [ patchdir [ stopversion ] [ -acxx ] ] ]
 #     The source directory defaults to /usr/src/linux, and the patch
@@ -28,7 +27,7 @@
 #       Nick Holloway <Nick.Holloway@alfie.demon.co.uk>, 2nd January 1995.
 #
 # Added support for handling multiple types of compression. What includes
-# gzip, bzip, bzip2, zip, compress, and plaintext.
+# gzip, bzip, bzip2, zip, compress, and plaintext. 
 #
 #       Adam Sulmicki <adam@cfar.umd.edu>, 1st January 1997.
 #
@@ -46,29 +45,16 @@
 # update usage message;
 # fix some whitespace damage;
 # be smarter about stopping when current version is larger than requested;
-#	Randy Dunlap <rdunlap@xenotime.net>, 2004-AUG-18.
-#
-# Add better support for (non-incremental) 2.6.x.y patches;
-# If an ending version number if not specified, the script automatically
-# increments the SUBLEVEL (x in 2.6.x.y) until no more patch files are found;
-# however, EXTRAVERSION (y in 2.6.x.y) is never automatically incremented
-# but must be specified fully.
-#
-# patch-kernel does not normally support reverse patching, but does so when
-# applying EXTRAVERSION (x.y) patches, so that moving from 2.6.11.y to 2.6.11.z
-# is easy and handled by the script (reverse 2.6.11.y and apply 2.6.11.z).
-#	Randy Dunlap <rdunlap@xenotime.net>, 2005-APR-08.
-
-PNAME=patch-kernel
+#	Randy Dunlap <rddunlap@osdl.org>, 2004-AUG-18.
 
 # Set directories from arguments, or use defaults.
 sourcedir=${1-/usr/src/linux}
 patchdir=${2-.}
 stopvers=${3-default}
 
-if [ "$1" = -h -o "$1" = --help -o ! -r "$sourcedir/Makefile" ]; then
+if [ "$1" == -h -o "$1" == --help -o ! -r "$sourcedir/Makefile" ]; then
 cat << USAGE
-usage: $PNAME [-h] [ sourcedir [ patchdir [ stopversion ] [ -acxx ] ] ]
+usage: patch-kernel [-h] [ sourcedir [ patchdir [ stopversion ] [ -acxx ] ] ]
   source directory defaults to /usr/src/linux,
   patch directory defaults to the current directory,
   stopversion defaults to <all in patchdir>.
@@ -85,19 +71,6 @@ do
 
 	esac;
 done
-
-# ---------------------------------------------------------------------------
-# arg1 is filename
-noFile () {
-	echo "cannot find patch file: ${patch}"
-	exit 1
-}
-
-# ---------------------------------------------------------------------------
-backwards () {
-	echo "$PNAME does not support reverse patching"
-	exit 1
-}
 
 # ---------------------------------------------------------------------------
 # Find a file, first parameter is basename of file
@@ -117,10 +90,6 @@ findFile () {
 		ext=".bz2"
 		name="bzip2"
 		uncomp="bunzip2 -dc"
-  elif [ -r ${filebase}.xz ]; then
-                ext=".xz"
-                name="xz"
-                uncomp="xz -dc"
   elif [ -r ${filebase}.zip ]; then
 		ext=".zip"
 		name="zip"
@@ -160,39 +129,15 @@ applyPatch () {
   fi
   # Remove backup files
   find $sourcedir/ '(' -name '*.orig' -o -name '.*.orig' ')' -exec rm -f {} \;
-
+ 
   return 0;
 }
 
-# ---------------------------------------------------------------------------
-# arg1 is patch filename
-reversePatch () {
-	echo -n "Reversing $1 (${name}) ... "
-	if $uncomp ${patchdir}/"$1"${ext} | patch -p1 -Rs -N -E -d $sourcedir
-	then
-		echo "done."
-	else
-		echo "failed.  Clean it up."
-		exit 1
-	fi
-	if [ "`find $sourcedir/ '(' -name '*.rej' -o -name '.*.rej' ')' -print`" ]
-	then
-		echo "Aborting.  Reject files found."
-		return 1
-	fi
-	# Remove backup files
-	find $sourcedir/ '(' -name '*.orig' -o -name '.*.orig' ')' -exec rm -f {} \;
-
-	return 0
-}
-
 # set current VERSION, PATCHLEVEL, SUBLEVEL, EXTRAVERSION
-# force $TMPFILEs below to be in local directory: a slash character prevents
-# the dot command from using the search path.
-TMPFILE=`mktemp ./.tmpver.XXXXXX` || { echo "cannot make temp file" ; exit 1; }
+TMPFILE=`mktemp .tmpver.XXXXXX` || { echo "cannot make temp file" ; exit 1; }
 grep -E "^(VERSION|PATCHLEVEL|SUBLEVEL|EXTRAVERSION)" $sourcedir/Makefile > $TMPFILE
 tr -d [:blank:] < $TMPFILE > $TMPFILE.1
-. $TMPFILE.1
+source $TMPFILE.1
 rm -f $TMPFILE*
 if [ -z "$VERSION" -o -z "$PATCHLEVEL" -o -z "$SUBLEVEL" ]
 then
@@ -209,99 +154,79 @@ echo "Current kernel version is $VERSION.$PATCHLEVEL.$SUBLEVEL${EXTRAVERSION} ($
 EXTRAVER=
 if [ x$EXTRAVERSION != "x" ]
 then
-	EXTRAVER=${EXTRAVERSION#.}
+	if [ ${EXTRAVERSION:0:1} == "." ]; then
+		EXTRAVER=${EXTRAVERSION:1}
+	else
+		EXTRAVER=$EXTRAVERSION
+	fi
 	EXTRAVER=${EXTRAVER%%[[:punct:]]*}
-	#echo "$PNAME: changing EXTRAVERSION from $EXTRAVERSION to $EXTRAVER"
+	#echo "patch-kernel: changing EXTRAVERSION from $EXTRAVERSION to $EXTRAVER"
 fi
 
 #echo "stopvers=$stopvers"
 if [ $stopvers != "default" ]; then
 	STOPSUBLEVEL=`echo $stopvers | cut -d. -f3`
 	STOPEXTRA=`echo $stopvers | cut -d. -f4`
-	STOPFULLVERSION=${stopvers%%.$STOPEXTRA}
-	#echo "#___STOPSUBLEVEL=/$STOPSUBLEVEL/, STOPEXTRA=/$STOPEXTRA/"
+	#echo "STOPSUBLEVEL=$STOPSUBLEVEL, STOPEXTRA=$STOPEXTRA"
 else
 	STOPSUBLEVEL=9999
 	STOPEXTRA=9999
 fi
 
-# This all assumes a 2.6.x[.y] kernel tree.
-# Don't allow backwards/reverse patching.
-if [ $STOPSUBLEVEL -lt $SUBLEVEL ]; then
-	backwards
-fi
-
-if [ x$EXTRAVER != "x" ]; then
-	CURRENTFULLVERSION="$VERSION.$PATCHLEVEL.$SUBLEVEL.$EXTRAVER"
-else
-	CURRENTFULLVERSION="$VERSION.$PATCHLEVEL.$SUBLEVEL"
-fi
-
-if [ x$EXTRAVER != "x" ]; then
-	echo "backing up to: $VERSION.$PATCHLEVEL.$SUBLEVEL"
-	patch="patch-${CURRENTFULLVERSION}"
-	findFile $patchdir/${patch} || noFile ${patch}
-	reversePatch ${patch} || exit 1
-fi
-
-# now current is 2.6.x, with no EXTRA applied,
-# so update to target SUBLEVEL (2.6.SUBLEVEL)
-# and then to target EXTRAVER (2.6.SUB.EXTRAVER) if requested.
-# If not ending sublevel is specified, it is incremented until
-# no further sublevels are found.
-
-if [ $STOPSUBLEVEL -gt $SUBLEVEL ]; then
 while :				# incrementing SUBLEVEL (s in v.p.s)
 do
-    CURRENTFULLVERSION="$VERSION.$PATCHLEVEL.$SUBLEVEL"
-    EXTRAVER=
-    if [ x$STOPFULLVERSION = x$CURRENTFULLVERSION ]; then
+    if [ x$EXTRAVER != "x" ]; then
+	CURRENTFULLVERSION="$VERSION.$PATCHLEVEL.$SUBLEVEL.$EXTRAVER"
+    else
+	CURRENTFULLVERSION="$VERSION.$PATCHLEVEL.$SUBLEVEL"
+    fi
+
+    if [ $stopvers == $CURRENTFULLVERSION ]; then
         echo "Stopping at $CURRENTFULLVERSION base as requested."
         break
     fi
 
-    SUBLEVEL=$(($SUBLEVEL + 1))
-    FULLVERSION="$VERSION.$PATCHLEVEL.$SUBLEVEL"
-    #echo "#___ trying $FULLVERSION ___"
+    while :			# incrementing EXTRAVER (x in v.p.s.x)
+    do
+	EXTRAVER=$((EXTRAVER + 1))
+	FULLVERSION="$VERSION.$PATCHLEVEL.$SUBLEVEL.$EXTRAVER"
+	#echo "... trying $FULLVERSION ..."
 
-    if [ $(($SUBLEVEL)) -gt $(($STOPSUBLEVEL)) ]; then
+	patch=patch-$FULLVERSION
+
+	# See if the file exists and find extension
+	findFile $patchdir/${patch} || break
+
+	# Apply the patch and check all is OK
+	applyPatch $patch || break
+
+	continue 2
+    done
+
+    EXTRAVER=
+    SUBLEVEL=$((SUBLEVEL + 1))
+    FULLVERSION="$VERSION.$PATCHLEVEL.$SUBLEVEL"
+    #echo "___ trying $FULLVERSION ___"
+
+    if [ $((SUBLEVEL)) -gt $((STOPSUBLEVEL)) ]; then
 	echo "Stopping since sublevel ($SUBLEVEL) is beyond stop-sublevel ($STOPSUBLEVEL)"
 	exit 1
     fi
 
     patch=patch-$FULLVERSION
+
     # See if the file exists and find extension
-    findFile $patchdir/${patch} || noFile ${patch}
+    findFile $patchdir/${patch} || break
 
     # Apply the patch and check all is OK
     applyPatch $patch || break
 done
-#echo "#___sublevel all done"
-fi
-
-# There is no incremental searching for extraversion...
-if [ "$STOPEXTRA" != "" ]; then
-while :				# just to allow break
-do
-# apply STOPEXTRA directly (not incrementally) (x in v.p.s.x)
-	FULLVERSION="$VERSION.$PATCHLEVEL.$SUBLEVEL.$STOPEXTRA"
-	#echo "#... trying $FULLVERSION ..."
-	patch=patch-$FULLVERSION
-
-	# See if the file exists and find extension
-	findFile $patchdir/${patch} || noFile ${patch}
-
-	# Apply the patch and check all is OK
-	applyPatch $patch || break
-	#echo "#___extraver all done"
-	break
-done
-fi
+#echo "base all done"
 
 if [ x$gotac != x ]; then
   # Out great user wants the -ac patches
 	# They could have done -ac (get latest) or -acxx where xx=version they want
-	if [ $gotac = "-ac" ]; then
+	if [ $gotac == "-ac" ]; then
 	  # They want the latest version
 		HIGHESTPATCH=0
 		for PATCHNAMES in $patchdir/patch-${CURRENTFULLVERSION}-ac*\.*
